name: frontend-ci
on:
  push:
    branches: [main]
    paths: [frontend/**]
  pull_request:
    branches: [main]
    paths: [frontend/**]

permissions:
  contents: read

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 23
      - name: install dependencies
        run: npm ci
      - name: eslint
        run: npm run lint

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 23
      - name: install dependencies
        run: npm ci
      - name: prettier
        run: npx prettier . --check
